# -*- coding: utf-8 -*-
# @Time    : 2021/3/3 5:39 下午
# @Author  : Ian Leto
# @File    : tucl.py
# 干啥的    : get 参数


data = {"Data": [
    {"ID": 1, "CreatedAt": "2019-12-13T16:21:17+08:00", "UpdatedAt": "2020-05-21T17:07:47+08:00", "ProjectName": "unet",
     "ProductName": "uver", "ServiceName": "uveragent", "ProjectID": "project-d54fcb48", "ProjectType": 0,
     "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:uver/uver.git", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0,
     "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "uver-3.0.1-x86_64.rpm", "StableConfVersion": "for_uver_v3.0.14", "ServiceCode": "101",
     "Usage": "", "SecUsage": "UVER"},
    {"ID": 2, "CreatedAt": "2019-12-13T16:24:34+08:00", "UpdatedAt": "2020-07-15T16:36:14+08:00", "ProjectName": "unet",
     "ProductName": "ulb4", "ServiceName": "ulb4agent", "ProjectID": "project-53c4524e", "ProjectType": 0,
     "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulb4.git", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0,
     "PromMode": 0, "ClusterGroup": 1, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "ulb4-3.0.1-24-g95b474e-x86_64.rpm", "StableConfVersion": "v0.0.72", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 3, "CreatedAt": "2019-12-13T16:26:00+08:00", "UpdatedAt": "2019-12-13T16:26:00+08:00", "ProjectName": "unet",
     "ProductName": "ulb7", "ServiceName": "ulbfe", "ProjectID": "project-9ff87d0e", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:ulb/ulbfe_go.git", "IsUse": 0, "IsDocker": 1, "DockerBucket": "iaas",
     "DockerAlias": "ulbfe", "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0,
     "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 1, "IsBranch": 0,
     "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 4, "CreatedAt": "2019-12-13T16:26:19+08:00", "UpdatedAt": "2020-11-24T15:55:14+08:00", "ProjectName": "unet",
     "ProductName": "cnat2", "ServiceName": "cnat2agent", "ProjectID": "project-3ddb39c3", "ProjectType": 0,
     "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/agent.git", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0,
     "PromMode": 0, "ClusterGroup": 1, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "cnat2agent-0.3.13-x86_64.rpm", "StableConfVersion": "v0.0.166", "ServiceCode": "", "Usage": "",
     "SecUsage": ""},
    {"ID": 5, "CreatedAt": "2019-12-13T16:26:50+08:00", "UpdatedAt": "2019-12-13T16:26:50+08:00", "ProjectName": "unet",
     "ProductName": "cnat", "ServiceName": "cnatops", "ProjectID": "project-75463433", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:unetsre/cnatops.git", "IsUse": 0, "IsDocker": 1, "DockerBucket": "cnat2",
     "DockerAlias": "cnatops", "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0,
     "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 6, "CreatedAt": "2019-12-13T16:27:18+08:00", "UpdatedAt": "2019-12-13T16:27:18+08:00", "ProjectName": "unet",
     "ProductName": "vpn", "ServiceName": "vpngwapi", "ProjectID": "project-63e52af5", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:vpngw/vpngw_api.git", "IsUse": 0, "IsDocker": 1, "DockerBucket": "vpngw",
     "DockerAlias": "vpngw_api", "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0,
     "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 7, "CreatedAt": "2019-12-13T16:27:39+08:00", "UpdatedAt": "2021-03-02T10:44:37+08:00", "ProjectName": "unet",
     "ProductName": "ulb7", "ServiceName": "ulblog-agent", "ProjectID": "project-68b5b7a3", "ProjectType": 0,
     "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulblog-agent.git", "IsUse": 0, "IsDocker": 0,
     "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "ulblog-agent-1.0.3-x86_64.rpm", "StableConfVersion": "ulblog-agent-1.0.0",
     "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 8, "CreatedAt": "2019-12-13T16:28:10+08:00", "UpdatedAt": "2021-02-26T14:50:40+08:00", "ProjectName": "unet",
     "ProductName": "ulb7", "ServiceName": "ulbapi", "ProjectID": "project-5b223e4e", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:ulb/ulb_api_go.git", "IsUse": 0, "IsDocker": 1, "DockerBucket": "iaas",
     "DockerAlias": "ulb-api", "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 1,
     "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 1, "IsBranch": 0,
     "StableVersion": "1.2.11", "StableConfVersion": "ulbapi-stable-0.0.17", "ServiceCode": "", "Usage": "",
     "SecUsage": ""},
    {"ID": 9, "CreatedAt": "2019-12-13T16:28:31+08:00", "UpdatedAt": "2020-05-21T17:12:44+08:00", "ProjectName": "unet",
     "ProductName": "uver", "ServiceName": "uverfe", "ProjectID": "project-22b0c202", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:uver/uverfe.git", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0,
     "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "uverfe-1.0.8-x86_64.rpm", "StableConfVersion": "for_uver_v3.0.14", "ServiceCode": "",
     "Usage": "", "SecUsage": "man-uverfe"},
    {"ID": 10, "CreatedAt": "2019-12-13T16:29:03+08:00", "UpdatedAt": "2019-12-13T16:29:03+08:00",
     "ProjectName": "unet", "ProductName": "vpn", "ServiceName": "vpngwdataapi", "ProjectID": "project-b3f0a48b",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:vpngw/vpngw_dataapi.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "vpngw", "DockerAlias": "vpngw_dataapi", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 11, "CreatedAt": "2019-12-13T16:29:30+08:00", "UpdatedAt": "2019-12-13T16:29:30+08:00",
                       "ProjectName": "unet", "ProductName": "vpn", "ServiceName": "vpngwmanager",
                       "ProjectID": "project-832aba4a", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:vpngw/vpngw_manager.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "vpngw", "DockerAlias": "vpngw_manager", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 12, "CreatedAt": "2019-12-13T16:30:04+08:00", "UpdatedAt": "2019-12-13T16:30:04+08:00",
     "ProjectName": "unet", "ProductName": "vpn", "ServiceName": "vpngwhypervisor", "ProjectID": "project-3bbf4648",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:vpngw/vpngw_hypervisor.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "vpngw", "DockerAlias": "vpngw_hypervisor", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 13, "CreatedAt": "2019-12-13T16:30:27+08:00", "UpdatedAt": "2019-12-13T16:30:27+08:00",
                       "ProjectName": "unet", "ProductName": "vpn", "ServiceName": "vpngwinternalapi",
                       "ProjectID": "project-6b3aca4b", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:vpngw/vpngw_internal_api.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "vpngw", "DockerAlias": "vpngw_internalapi", "Unit": "process",
                       "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
                       "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
                       "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 14, "CreatedAt": "2019-12-13T16:30:54+08:00", "UpdatedAt": "2021-02-26T14:47:48+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulbmonitor", "ProjectID": "project-64526d46",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulb_monitor_go.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 1, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "ulbmonitor-3.3.0-x86_64.rpm",
     "StableConfVersion": "ulbmonitor-OuterIPV4-1.0.0", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 15, "CreatedAt": "2019-12-13T16:31:17+08:00", "UpdatedAt": "2020-11-24T15:55:29+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2monitor", "ProjectID": "project-edd7ce50",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/cnat2monitor.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "cnat2monitor-0.4.8-x86_64.rpm", "StableConfVersion": "v0.0.166",
     "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 16, "CreatedAt": "2019-12-13T16:31:33+08:00", "UpdatedAt": "2020-05-21T17:08:15+08:00",
     "ProjectName": "unet", "ProductName": "uver", "ServiceName": "uver-extern-scripts",
     "ProjectID": "project-11de9bd2", "ProjectType": 0, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:uver/uver-extern-scripts.git", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0,
     "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "uver-extern-scripts-3.0.2-x86_64.rpm", "StableConfVersion": "for_uver_v3.0.14",
     "ServiceCode": "", "Usage": "", "SecUsage": "UVER"},
    {"ID": 17, "CreatedAt": "2019-12-13T16:31:49+08:00", "UpdatedAt": "2020-05-21T17:08:22+08:00",
     "ProjectName": "unet", "ProductName": "uver", "ServiceName": "stats-monitor", "ProjectID": "project-72e0df80",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:uver/stats-monitor.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "stats-monitor-3.0.1-x86_64.rpm",
     "StableConfVersion": "for_uver_v3.0.14", "ServiceCode": "", "Usage": "", "SecUsage": "UVER"},
    {"ID": 22, "CreatedAt": "2019-12-16T15:26:01+08:00", "UpdatedAt": "2019-12-16T15:26:01+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulbmanager", "ProjectID": "project-15493eec",
     "ProjectType": 0, "IsStatus": 0, "GitRepo": "git@git.ucloudadmin.com:ulb/ulb_manager_go.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 23, "CreatedAt": "2019-12-16T19:22:13+08:00", "UpdatedAt": "2021-02-26T14:51:46+08:00",
                       "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "int_ulbagent",
                       "ProjectID": "project-44996e0e", "ProjectType": 0, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:ulb/ulb_agent_intranet.git", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 1,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 1,
                       "StableVersion": "ulbagent-1.2.1-x86_64.rpm", "StableConfVersion": "int_ulbagent-1.1.1",
                       "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 24, "CreatedAt": "2019-12-17T11:43:57+08:00", "UpdatedAt": "2019-12-17T11:43:57+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "unetfe", "ProjectID": "project-40972f15",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/unetfe.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "iaas", "DockerAlias": "unetfe", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 1, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 28, "CreatedAt": "2019-12-17T14:26:52+08:00", "UpdatedAt": "2020-11-16T16:27:11+08:00",
                       "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "natops",
                       "ProjectID": "project-e99af1a5", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:cnat2/natops.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "cnat2", "DockerAlias": "natops", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v0.2.2",
                       "StableConfVersion": "v0.0.161", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 34, "CreatedAt": "2019-12-17T16:19:31+08:00", "UpdatedAt": "2020-11-16T16:27:15+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2pinger", "ProjectID": "project-197c3eed",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/pinger.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "cnat2", "DockerAlias": "pinger", "Unit": "process", "ConfArea": "zone", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "v0.0.4", "StableConfVersion": "v0.0.161", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 35, "CreatedAt": "2019-12-17T16:29:00+08:00", "UpdatedAt": "2019-12-17T16:29:00+08:00",
                       "ProjectName": "unet", "ProductName": "ulb4", "ServiceName": "ulb4alarm",
                       "ProjectID": "project-e47002b2", "ProjectType": 0, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:ulb/ulb4-alarm.git", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 1,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 36, "CreatedAt": "2019-12-17T16:29:15+08:00", "UpdatedAt": "2019-12-17T16:29:15+08:00",
     "ProjectName": "unet", "ProductName": "ulb4", "ServiceName": "ulb4monitor", "ProjectID": "project-ea3e3073",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulb4_monitor.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 1, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 40, "CreatedAt": "2019-12-17T20:10:33+08:00", "UpdatedAt": "2019-12-17T20:10:33+08:00",
                       "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uhost-manager",
                       "ProjectID": "project-c318deb2", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git.ucloudadmin.com/uhost/uhost/tree/master/uhost-manager", "IsUse": 0,
                       "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 1, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 42, "CreatedAt": "2019-12-18T21:01:32+08:00", "UpdatedAt": "2019-12-18T21:01:32+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "cnat2_utrafficmanager",
     "ProjectID": "project-e0ffb160", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:utraffic/utrafficmanager.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "iaas", "DockerAlias": "cnat2_utrafficmanager", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 43, "CreatedAt": "2019-12-20T15:22:39+08:00", "UpdatedAt": "2019-12-20T15:22:39+08:00",
                       "ProjectName": "unet", "ProductName": "eip", "ServiceName": "vpn_utrafficmanager",
                       "ProjectID": "project-67e2ea35", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:utraffic/utrafficmanager.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "iaas", "DockerAlias": "utrafficmanager", "Unit": "process", "ConfArea": "zone",
                       "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 45, "CreatedAt": "2019-12-20T16:55:15+08:00", "UpdatedAt": "2020-11-16T16:27:18+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2setapi", "ProjectID": "project-680eabcf",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/setapi.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "cnat2", "DockerAlias": "setapi", "Unit": "process", "ConfArea": "set", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "v0.1.0", "StableConfVersion": "v0.0.161", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 46, "CreatedAt": "2019-12-20T17:15:41+08:00", "UpdatedAt": "2020-11-16T16:27:21+08:00",
                       "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2apiserver",
                       "ProjectID": "project-2206d0d5", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:cnat2/apiserver.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "cnat2", "DockerAlias": "apiserver", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v0.1.9",
                       "StableConfVersion": "v0.0.161", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 47, "CreatedAt": "2019-12-23T11:33:35+08:00", "UpdatedAt": "2020-11-16T16:27:25+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2aftermath", "ProjectID": "project-3f4a1395",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/aftermath.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "cnat2", "DockerAlias": "aftermath", "Unit": "process", "ConfArea": "set",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v0.2.1", "StableConfVersion": "v0.0.161", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 48, "CreatedAt": "2019-12-23T11:53:08+08:00", "UpdatedAt": "2020-11-16T16:19:15+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "scheduler", "ProjectID": "project-e01d3896",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/scheduler.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "cnat2", "DockerAlias": "scheduler", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v0.1.0", "StableConfVersion": "v0.0.161", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 49, "CreatedAt": "2019-12-23T14:01:56+08:00", "UpdatedAt": "2020-11-16T16:27:31+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2transfer", "ProjectID": "project-b3e8fe57",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/transfer.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "cnat2", "DockerAlias": "transfer", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v0.2.2", "StableConfVersion": "v0.0.161", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 51, "CreatedAt": "2019-12-24T16:38:45+08:00", "UpdatedAt": "2020-11-16T16:27:34+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2evthub", "ProjectID": "project-8716b38f",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/evthub.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "cnat2", "DockerAlias": "evthub", "Unit": "process", "ConfArea": "region", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "v0.0.6", "StableConfVersion": "v0.0.161", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 52, "CreatedAt": "2019-12-24T17:19:37+08:00", "UpdatedAt": "2020-11-16T16:27:38+08:00",
                       "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2routeservice",
                       "ProjectID": "project-6e004f09", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:cnat2/routeservice.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "cnat2", "DockerAlias": "routeservice", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v0.2.18",
                       "StableConfVersion": "v0.0.161", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 62, "CreatedAt": "2019-12-24T18:44:26+08:00", "UpdatedAt": "2020-11-16T16:19:27+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2bwmanager", "ProjectID": "project-e83f10cd",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/bwmanager.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "cnat2", "DockerAlias": "bwmanager", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v0.2.13", "StableConfVersion": "v0.0.161", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 63, "CreatedAt": "2019-12-24T19:06:43+08:00", "UpdatedAt": "2019-12-24T19:06:43+08:00",
     "ProjectName": "unet", "ProductName": "sdnbox", "ServiceName": "sdnboxcontroller", "ProjectID": "project-97b4843f",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:sdnbox/sdnboxcontroller.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "iaas", "DockerAlias": "sdnboxcontroller", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 65, "CreatedAt": "2019-12-26T19:01:56+08:00", "UpdatedAt": "2019-12-26T19:01:56+08:00",
                       "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uhost-api",
                       "ProjectID": "project-2d8b6ad6", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:uhostsre/uhost.git", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 1, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 67, "CreatedAt": "2020-01-03T18:02:06+08:00", "UpdatedAt": "2020-11-16T16:27:43+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2manager", "ProjectID": "project-19aec99b",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/manager.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "cnat2", "DockerAlias": "manager", "Unit": "process", "ConfArea": "set", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "v0.2.7", "StableConfVersion": "v0.0.161", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 68, "CreatedAt": "2020-01-08T15:20:22+08:00", "UpdatedAt": "2020-01-08T15:20:22+08:00",
                       "ProjectName": "unet", "ProductName": "ulb4", "ServiceName": "ulb4ops",
                       "ProjectID": "project-448c9b93", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:ulb/ulb4ops.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "iaas", "DockerAlias": "ulb4ops", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 70, "CreatedAt": "2020-01-08T16:59:58+08:00", "UpdatedAt": "2020-11-16T16:27:49+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2flowservice", "ProjectID": "project-17d7ad99",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/flowservice.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "cnat2", "DockerAlias": "flowservice", "Unit": "process", "ConfArea": "set",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v0.1.3", "StableConfVersion": "v0.0.161", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 71, "CreatedAt": "2020-01-08T17:01:07+08:00", "UpdatedAt": "2020-11-16T16:27:52+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2bw", "ProjectID": "project-14f3553d",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/cnat2bw.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "cnat2", "DockerAlias": "cnat2bw", "Unit": "process", "ConfArea": "set", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "v0.0.6", "StableConfVersion": "v0.0.161", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 72, "CreatedAt": "2020-01-08T17:06:19+08:00", "UpdatedAt": "2020-07-15T16:39:14+08:00",
                       "ProjectName": "unet", "ProductName": "ulb4", "ServiceName": "ulb4managerbe",
                       "ProjectID": "project-d8e7172b", "ProjectType": 0, "IsStatus": 0,
                       "GitRepo": "git@git.ucloudadmin.com:ulb/ulb4manager.git", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
                       "StableVersion": "ULB4ManagerBe-3.0.2-x86_64.rpm", "StableConfVersion": "v0.0.72",
                       "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 73, "CreatedAt": "2020-01-08T17:06:48+08:00", "UpdatedAt": "2020-01-08T17:06:48+08:00",
     "ProjectName": "unet", "ProductName": "ulb4", "ServiceName": "ulb4managerfe", "ProjectID": "project-618edfa5",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulb4manager_fe.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 74, "CreatedAt": "2020-01-08T17:07:12+08:00", "UpdatedAt": "2020-01-08T17:07:12+08:00",
                       "ProjectName": "unet", "ProductName": "ulb4", "ServiceName": "ulb4hc",
                       "ProjectID": "project-e6f43a24", "ProjectType": 0, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:ulb/ulb4-health-check.git", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 75, "CreatedAt": "2020-01-09T16:00:14+08:00", "UpdatedAt": "2020-01-09T16:00:14+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulbmanagerfe", "ProjectID": "project-53129840",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulbmanager_fe.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 1, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 76, "CreatedAt": "2020-02-05T11:15:56+08:00", "UpdatedAt": "2020-05-21T17:13:08+08:00",
                       "ProjectName": "unet", "ProductName": "uver", "ServiceName": "uverops",
                       "ProjectID": "project-4ab917fa", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:uver/uverops.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "iaas", "DockerAlias": "uverops", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v1.0.12",
                       "StableConfVersion": "for_uver_v3.0.14", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 77, "CreatedAt": "2020-02-12T17:04:41+08:00", "UpdatedAt": "2020-02-12T17:04:41+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "anycast-api", "ProjectID": "project-bbb3aa8e",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "https://git.ucloudadmin.com/utraffic/anycast-api", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "iaas", "DockerAlias": "anycastapi", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 1, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 79, "CreatedAt": "2020-02-20T12:42:13+08:00", "UpdatedAt": "2020-02-20T12:42:13+08:00",
                       "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulb7ops",
                       "ProjectID": "project-e53abd1d", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:ulb/ulb7ops.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "iaas", "DockerAlias": "ulb7ops", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 80, "CreatedAt": "2020-03-02T11:33:10+08:00", "UpdatedAt": "2020-05-21T17:12:54+08:00",
     "ProjectName": "unet", "ProductName": "uver", "ServiceName": "uverbe", "ProjectID": "project-f57966b7",
     "ProjectType": 0, "IsStatus": 0, "GitRepo": "git@git.ucloudadmin.com:uver/uverbe.git", "IsUse": 0, "IsDocker": 0,
     "DockerBucket": "", "DockerAlias": "", "Unit": "pocess", "ConfArea": "region", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "uverbe从数据库拉取信息，生成配置文件，同步给uveragent使用。",
     "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "UVERManager-2.0.7-x86_64.rpm",
     "StableConfVersion": "for_uver_v3.0.14", "ServiceCode": "", "Usage": "", "SecUsage": "man-uverbe"},
    {"ID": 83, "CreatedAt": "2020-03-02T18:24:22+08:00", "UpdatedAt": "2020-11-16T16:27:57+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2badassbuster", "ProjectID": "project-4a5e670b",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/badassbuster.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "cnat2", "DockerAlias": "badassbuster", "Unit": "host", "ConfArea": "set",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v0.2.2", "StableConfVersion": "v0.0.161", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 84, "CreatedAt": "2020-03-02T18:26:29+08:00", "UpdatedAt": "2020-11-16T16:28:00+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2uxrhub", "ProjectID": "project-0f29b05c",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/uxrhub.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "cnat2", "DockerAlias": "uxrhub", "Unit": "host", "ConfArea": "region", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "v0.0.2", "StableConfVersion": "v0.0.161", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 85, "CreatedAt": "2020-03-03T14:10:09+08:00", "UpdatedAt": "2020-03-03T14:10:09+08:00",
                       "ProjectName": "ufile", "ProductName": "middleware", "ServiceName": "filebeat",
                       "ProjectID": "project-14a15cc6", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:ufile-sre/elk-config.git", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "pocess", "ConfArea": "region",
                       "EffectRange": "global", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 86, "CreatedAt": "2020-03-03T14:20:52+08:00", "UpdatedAt": "2021-02-24T17:20:24+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulbagent", "ProjectID": "project-7497efb0",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulb_agent_go.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "pocess", "ConfArea": "set", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 1, "Comment": "外网ulb7的haproxy版本agent", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "ulbagent-3.1.1-x86_64.rpm",
     "StableConfVersion": "ulbagent-0.0.1", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 87, "CreatedAt": "2020-03-03T17:26:28+08:00", "UpdatedAt": "2020-03-03T17:26:28+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "libvirt", "ProjectID": "project-b3264cdb",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "host", "ConfArea": "zone", "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0,
     "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 88, "CreatedAt": "2020-03-03T22:11:44+08:00", "UpdatedAt": "2020-03-03T22:11:44+08:00",
     "ProjectName": "uplatform", "ProductName": "filebeat", "ServiceName": "ufileprxoy",
     "ProjectID": "project-1c7a410d", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:ufile-sre/elk-config.git", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "pocess", "ConfArea": "region", "EffectRange": "global", "GrpcMode": 0, "HttpMode": 0,
     "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 89, "CreatedAt": "2020-03-03T22:17:06+08:00", "UpdatedAt": "2020-03-03T22:17:06+08:00",
     "ProjectName": "uplatform", "ProductName": "filebeat", "ServiceName": "filebeat_ufileproxy",
     "ProjectID": "project-2204faca", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:ufile-sre/elk-config.git", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "pocess", "ConfArea": "region", "EffectRange": "global", "GrpcMode": 0, "HttpMode": 0,
     "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 91, "CreatedAt": "2020-03-04T16:39:26+08:00", "UpdatedAt": "2020-03-04T16:39:26+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "ulb4_utrafficmanager",
     "ProjectID": "project-96e736c0", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:utraffic/utrafficmanager.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "iaas", "DockerAlias": "utrafficmanager", "Unit": "host", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "ulb4_utrafficmanager走docker化部署", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 92, "CreatedAt": "2020-03-04T20:12:19+08:00", "UpdatedAt": "2020-03-04T20:12:19+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "share_bandwidth_utrafficmanager",
     "ProjectID": "project-5873e570", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:utraffic/utrafficmanager.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "iaas", "DockerAlias": "utrafficmanager", "Unit": "pocess", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "share_bandwidth_utrafficmanager", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 94, "CreatedAt": "2020-03-04T22:38:12+08:00", "UpdatedAt": "2020-03-04T22:38:12+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "ulb7_utrafficmanager",
     "ProjectID": "project-ea0391bb", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:utraffic/utrafficmanager.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "iaas", "DockerAlias": "ulb7_utrafficmanager", "Unit": "host", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "ulb7_utrafficmanager", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 95, "CreatedAt": "2020-03-09T16:45:08+08:00", "UpdatedAt": "2020-03-09T16:45:08+08:00",
     "ProjectName": "unet", "ProductName": "sre", "ServiceName": "moss", "ProjectID": "project-ed12067e",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "pocess", "ConfArea": "region", "EffectRange": "global", "GrpcMode": 0, "HttpMode": 0,
     "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 96, "CreatedAt": "2020-03-11T18:09:46+08:00", "UpdatedAt": "2020-03-11T18:09:46+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2provision", "ProjectID": "project-9602a738",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "cnat2provision", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "pocess", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0,
     "PromMode": 0, "ClusterGroup": 0, "Comment": "cnat2provision", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 97, "CreatedAt": "2020-03-11T18:59:51+08:00", "UpdatedAt": "2020-03-11T18:59:51+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "cnat_utrafficmanager",
     "ProjectID": "project-17e21ac8", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:utraffic/utrafficmanager.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "iaas", "DockerAlias": "utrafficmanager", "Unit": "host", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "cnat_utrafficmanager", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 98, "CreatedAt": "2020-03-17T21:08:32+08:00", "UpdatedAt": "2020-03-17T21:08:32+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "cnat2_traffic", "ProjectID": "project-7b9029ea",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/cnat2_traffic.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "cnat2_traffic", "Unit": "pocess", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 99, "CreatedAt": "2020-03-26T18:49:22+08:00", "UpdatedAt": "2020-03-26T18:49:22+08:00",
                       "ProjectName": "unet", "ProductName": "vpn", "ServiceName": "vpngw_monitor",
                       "ProjectID": "project-d8178a73", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:vpngw/vpngw_monitor.git", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 1, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "vpngw_monitor", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 100, "CreatedAt": "2020-04-07T18:24:38+08:00", "UpdatedAt": "2020-04-07T18:24:38+08:00",
     "ProjectName": "unet", "ProductName": "vpn", "ServiceName": "vpngw_agent", "ProjectID": "project-40c21832",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:vpngw/vpngw_agent.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 1, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 101, "CreatedAt": "2020-04-23T19:45:17+08:00", "UpdatedAt": "2020-04-23T19:45:17+08:00",
                       "ProjectName": "umiddleware", "ProductName": "udatabase", "ServiceName": "udatabase",
                       "ProjectID": "project-89664bfa", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:udatabase/udatabase.git", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "udatabase", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 102, "CreatedAt": "2020-05-27T16:19:16+08:00", "UpdatedAt": "2020-05-27T16:19:16+08:00",
     "ProjectName": "unet", "ProductName": "udns", "ServiceName": "udnsmanager", "ProjectID": "project-4407cca9",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:udns/udnsmanager.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 103, "CreatedAt": "2020-05-28T12:50:20+08:00", "UpdatedAt": "2020-05-28T12:50:20+08:00",
                       "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulb_bwmanager",
                       "ProjectID": "project-5e771c1c", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:ulb/ulb_bwmanager.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "iaas", "DockerAlias": "ulb_bwmanager", "Unit": "host", "ConfArea": "set",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "ulb bwmanager服务", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 105, "CreatedAt": "2020-06-01T16:02:46+08:00", "UpdatedAt": "2020-06-01T16:02:46+08:00",
     "ProjectName": "udisk", "ProductName": "udisk", "ServiceName": "chunk", "ProjectID": "project-f5f9c37a",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "set", "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "udisk_test", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 106, "CreatedAt": "2020-06-01T17:40:56+08:00", "UpdatedAt": "2020-06-01T17:40:56+08:00",
     "ProjectName": "udisk", "ProductName": "udisk", "ServiceName": "metaserver", "ProjectID": "project-e8053560",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "https://git.ucloudadmin.com/block/metaserver.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set", "EffectRange": "zone",
     "GrpcMode": 0, "HttpMode": 1, "PromMode": 0, "ClusterGroup": 1, "Comment": "metaserver_test", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 107, "CreatedAt": "2020-06-02T11:54:57+08:00", "UpdatedAt": "2021-02-26T14:52:37+08:00",
                       "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulb7alarm",
                       "ProjectID": "project-ba87360f", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:ulb/ulb7-alarm.git", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "host", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
                       "StableVersion": "ulb7alarm-1.0.1-x86_64.rpm", "StableConfVersion": "ulb7alarm-1.0.1",
                       "ServiceCode": "", "Usage": "", "SecUsage": "GULB"},
    {"ID": 108, "CreatedAt": "2020-06-08T11:30:24+08:00", "UpdatedAt": "2020-06-08T11:30:24+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "hc_master", "ProjectID": "project-acde802c",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/hc_master.git", "IsUse": 0, "IsDocker": 0,
     "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 1,
     "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 110, "CreatedAt": "2020-06-12T16:50:58+08:00", "UpdatedAt": "2020-06-12T16:50:58+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulb_bwagent", "ProjectID": "project-3121ba5a",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulb_bwagent.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "ulb数据面带宽管理服务",
     "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 111, "CreatedAt": "2020-06-15T16:57:05+08:00", "UpdatedAt": "2020-06-15T16:57:05+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "uscan_eip", "ProjectID": "project-6e6b7ad4",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "https://git.ucloudadmin.com/utraffic/uscan-eip", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "uscan-eip", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 1, "ClusterGroup": 0, "Comment": "eip 扫描服务",
     "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 112, "CreatedAt": "2020-06-15T19:05:34+08:00", "UpdatedAt": "2020-06-15T19:05:34+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulbclusterhc", "ProjectID": "project-0780072f",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulb-cluster-health-check.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 1, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 113, "CreatedAt": "2020-07-02T11:50:44+08:00", "UpdatedAt": "2020-07-02T11:50:44+08:00",
                       "ProjectName": "unet", "ProductName": "eip", "ServiceName": "utraffic-monitor",
                       "ProjectID": "project-3c6d3a58", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "https://git.ucloudadmin.com/utraffic/utraffic-monitor", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "utraffic", "DockerAlias": "utraffic-monitor", "Unit": "process",
                       "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 1,
                       "ClusterGroup": 0, "Comment": "eip监控服务", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
                       "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 114, "CreatedAt": "2020-07-03T15:23:13+08:00", "UpdatedAt": "2020-07-03T15:23:13+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "sharebandwidth-postpaid",
     "ProjectID": "project-9eb8c7c5", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:utraffic/sharebandwidth_postpaid.git", "IsUse": 0, "IsDocker": 0,
     "DockerBucket": "", "DockerAlias": "", "Unit": "host", "ConfArea": "region", "EffectRange": "global",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 115, "CreatedAt": "2020-07-10T16:19:17+08:00", "UpdatedAt": "2020-07-10T16:19:17+08:00",
     "ProjectName": "dpagent", "ProductName": "vnpd-vpc3", "ServiceName": "vnpd", "ProjectID": "project-4e6ee5ae",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:vnpd-vpc3/dpagent.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "host", "ConfArea": "region",
     "EffectRange": "global", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 116, "CreatedAt": "2020-07-10T16:20:18+08:00", "UpdatedAt": "2020-09-03T14:54:01+08:00",
                       "ProjectName": "vnpd", "ProductName": "vnpd-vpc3", "ServiceName": "dpagent",
                       "ProjectID": "project-53f1e515", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:vnpd-vpc3/dpagent.git", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "host", "ConfArea": "region",
                       "EffectRange": "global", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
                       "StableVersion": "dpagent-v0.4.26-x86_64.rpm", "StableConfVersion": "v0.0.120",
                       "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 118, "CreatedAt": "2020-07-10T16:23:25+08:00", "UpdatedAt": "2020-07-10T16:23:25+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uhost-tracker", "ProjectID": "project-97b6a118",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:uhost/uhost.git", "IsUse": 0, "IsDocker": 0,
     "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set", "EffectRange": "zone", "GrpcMode": 0,
     "HttpMode": 0, "PromMode": 0, "ClusterGroup": 1, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 119, "CreatedAt": "2020-07-10T16:26:14+08:00", "UpdatedAt": "2020-07-10T16:26:14+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uhost-scheduler", "ProjectID": "project-205f5175",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:uhost/uhost-go.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set", "EffectRange": "zone",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 1, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 120, "CreatedAt": "2020-07-10T16:27:26+08:00", "UpdatedAt": "2020-07-10T16:27:26+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uimage3-access", "ProjectID": "project-c661c25d",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@gitlab.ucloudadmin.com:uhost/uimage3.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set", "EffectRange": "zone",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 1, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 121, "CreatedAt": "2020-07-10T16:28:17+08:00", "UpdatedAt": "2020-07-10T16:28:17+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uimage3-manager", "ProjectID": "project-54a0b15e",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@gitlab.ucloudadmin.com:uhost/uimage3.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set", "EffectRange": "zone",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 1, "Comment": "", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 122, "CreatedAt": "2020-07-13T10:42:50+08:00", "UpdatedAt": "2020-07-13T10:42:50+08:00",
     "ProjectName": "unet", "ProductName": "vpn", "ServiceName": "vpngwops", "ProjectID": "project-e1792a9c",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:vpngw/vpngwops.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "iaas", "DockerAlias": "vpngwops", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "vpngw ops",
     "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 123, "CreatedAt": "2020-07-15T14:47:50+08:00", "UpdatedAt": "2020-07-15T14:47:50+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "sslextender", "ProjectID": "project-16b068df",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/sslextender.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "iaas", "DockerAlias": "sslextender", "Unit": "host", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "SSLExtender服务", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 124, "CreatedAt": "2020-07-15T15:33:33+08:00", "UpdatedAt": "2020-07-15T15:33:33+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uhost-action", "ProjectID": "project-adb6f304",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": "uhost|ssd|gpu|rdma-sriov"},
    {"ID": 125, "CreatedAt": "2020-07-15T15:33:50+08:00", "UpdatedAt": "2020-07-15T15:33:50+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "host-agent", "ProjectID": "project-d2fddea8",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": "uhost|ssd|gpu|rdma-sriov"},
    {"ID": 126, "CreatedAt": "2020-07-15T15:34:09+08:00", "UpdatedAt": "2020-07-15T15:34:09+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "eventq-agent", "ProjectID": "project-98e5287d",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": "uhost|ssd|gpu|rdma-sriov"},
    {"ID": 127, "CreatedAt": "2020-07-15T15:34:29+08:00", "UpdatedAt": "2020-07-15T15:34:29+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "mg-agent", "ProjectID": "project-544f3767",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": "uhost|ssd|gpu|rdma-sriov"},
    {"ID": 128, "CreatedAt": "2020-07-15T15:34:46+08:00", "UpdatedAt": "2020-07-15T15:34:46+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "rsc-service", "ProjectID": "project-3100bfaf",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": "uhost|ssd|gpu|rdma-sriov"},
    {"ID": 129, "CreatedAt": "2020-07-15T15:38:49+08:00", "UpdatedAt": "2020-07-15T15:38:49+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "udisk-agent", "ProjectID": "project-93413422",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": "uhost|ssd|gpu|rdma-sriov"},
    {"ID": 130, "CreatedAt": "2020-07-15T15:39:06+08:00", "UpdatedAt": "2020-07-15T15:39:06+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "unet-agent", "ProjectID": "project-3b026dee",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": "uhost|ssd|gpu|rdma-sriov"},
    {"ID": 131, "CreatedAt": "2020-07-15T15:52:04+08:00", "UpdatedAt": "2020-07-15T15:52:04+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "trafficmon_proxy", "ProjectID": "project-22b052a1",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/trafficmon_proxy.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "trafficmon_proxy", "Unit": "process",
     "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 1, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "",
     "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 132, "CreatedAt": "2020-07-15T15:56:25+08:00", "UpdatedAt": "2020-07-15T15:56:25+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uhost-virtual", "ProjectID": "project-7f7da903",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": "uhost|ssd|gpu|rdma-sriov"},
    {"ID": 133, "CreatedAt": "2020-07-16T17:04:19+08:00", "UpdatedAt": "2020-07-16T17:04:19+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "traffic_driver", "ProjectID": "project-f33745a2",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/traffic_driver.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "traffic_driver", "Unit": "process",
     "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 1, "ClusterGroup": 0,
     "Comment": "新版带宽驱动模块", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "",
     "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 134, "CreatedAt": "2020-07-16T21:31:31+08:00", "UpdatedAt": "2020-07-16T21:31:31+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "trafficmon_prom", "ProjectID": "project-ce9e8e31",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/trafficmon_prometheus.git",
     "IsUse": 0, "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "trafficmon_prom", "Unit": "process",
     "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 1, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "",
     "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 136, "CreatedAt": "2020-07-17T11:58:34+08:00", "UpdatedAt": "2020-07-17T11:58:34+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "traffic_calculator", "ProjectID": "project-4b7c8479",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/traffic_calculator.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "traffic_calculator", "Unit": "process",
     "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 1, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "",
     "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 137, "CreatedAt": "2020-07-17T11:59:24+08:00", "UpdatedAt": "2020-07-17T11:59:24+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "traffic_ulb7agent", "ProjectID": "project-a6e9eef2",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/traffic_ulb7agent.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "traffic_ulb7agent", "Unit": "process",
     "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "",
     "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 138, "CreatedAt": "2020-07-17T15:15:17+08:00", "UpdatedAt": "2020-07-17T15:15:17+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "traffic_coreapi", "ProjectID": "project-7b2b8cf5",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/coreapi.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "coreapi", "Unit": "process", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 139, "CreatedAt": "2020-07-17T16:02:35+08:00", "UpdatedAt": "2020-07-17T16:02:35+08:00",
                       "ProjectName": "unet", "ProductName": "eip", "ServiceName": "traffic_metamanager",
                       "ProjectID": "project-69f73776", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:utraffic/metamanager.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "utraffic", "DockerAlias": "metamanager", "Unit": "process",
                       "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1,
                       "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
                       "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 140, "CreatedAt": "2020-07-20T15:55:16+08:00", "UpdatedAt": "2020-07-20T15:55:16+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "utraffic_billing", "ProjectID": "project-92707542",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/utraffic_billing.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "host", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 141, "CreatedAt": "2020-07-24T15:54:47+08:00", "UpdatedAt": "2020-07-24T15:54:47+08:00",
                       "ProjectName": "umiddleware", "ProductName": "tundra", "ServiceName": "mongo",
                       "ProjectID": "project-a9dedce5", "ProjectType": 1, "IsStatus": 1, "GitRepo": "", "IsUse": 0,
                       "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 142, "CreatedAt": "2020-07-31T17:53:21+08:00", "UpdatedAt": "2020-07-31T17:53:21+08:00",
     "ProjectName": "umiddleware", "ProductName": "udns", "ServiceName": "dns_exporter",
     "ProjectID": "project-db1ca789", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:uhostsre/dns_exporter.git", "IsUse": 0, "IsDocker": 0, "DockerBucket": "",
     "DockerAlias": "", "Unit": "process", "ConfArea": "region", "EffectRange": "global", "GrpcMode": 0, "HttpMode": 1,
     "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 143, "CreatedAt": "2020-08-06T14:31:38+08:00", "UpdatedAt": "2020-08-06T14:31:38+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "bwm_adaptor", "ProjectID": "project-2b6f101d",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/bwm_adaptor.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "bwm_adaptor", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 0, "ClusterGroup": 0, "Comment": "bwm_adaptor",
     "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 144, "CreatedAt": "2020-08-11T13:59:46+08:00", "UpdatedAt": "2020-08-11T13:59:46+08:00",
     "ProjectName": "uwaf", "ProductName": "usec", "ServiceName": "waf_domain_monitor", "ProjectID": "project-6278c05a",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 1, "DockerBucket": "uwaf",
     "DockerAlias": "uwaf/domain_monitor", "Unit": "host", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0,
     "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 145, "CreatedAt": "2020-08-25T18:00:12+08:00", "UpdatedAt": "2021-02-26T14:48:38+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "haproxy", "ProjectID": "project-d8b76290",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "zone", "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "HAProxy", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "haproxy-1.7.5-1.el7.x86_64.rpm", "StableConfVersion": "v0.0.214", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 146, "CreatedAt": "2020-08-25T18:06:15+08:00", "UpdatedAt": "2020-08-25T18:06:15+08:00",
                       "ProjectName": "unet", "ProductName": "eip", "ServiceName": "ulb7_utrafficagent",
                       "ProjectID": "project-88b8ba5b", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "https://git.ucloudadmin.com/utraffic/utrafficagent", "IsUse": 0, "IsDocker": 0,
                       "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "zone",
                       "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "ulb7 utrafficagent 旧版", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
                       "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 147, "CreatedAt": "2020-08-27T11:43:24+08:00", "UpdatedAt": "2020-08-27T11:43:24+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "cnat2_bwm_adaptor", "ProjectID": "project-f3e51a3d",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/bwm_adaptor.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "bwm_adaptor", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0,
     "Comment": "适配业务侧接入新版带宽系统程序", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 148, "CreatedAt": "2020-08-27T11:45:57+08:00", "UpdatedAt": "2020-08-27T11:45:57+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "cnat_bwm_adaptor", "ProjectID": "project-551beef9",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/bwm_adaptor.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "bwm_adaptor", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0,
     "Comment": "适配业务侧接入新版带宽系统程序", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 149, "CreatedAt": "2020-08-27T11:47:19+08:00", "UpdatedAt": "2020-08-27T11:47:19+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "ulb4_bwm_adaptor", "ProjectID": "project-8778d26a",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/bwm_adaptor.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "bwm_adaptor", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0, "Comment": "适配业务系统接入新版系统程序",
     "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 150, "CreatedAt": "2020-08-27T11:48:42+08:00", "UpdatedAt": "2020-08-27T11:48:42+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "vpn_bwm_adaptor", "ProjectID": "project-e3de0c74",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/bwm_adaptor.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "bwm_adaptor", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0, "Comment": "适配业务侧接入新版系统程序",
     "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 151, "CreatedAt": "2020-08-28T10:49:10+08:00", "UpdatedAt": "2020-08-28T10:49:10+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "ulb7_bwm_adaptor", "ProjectID": "project-ff656e7e",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:utraffic/bwm_adaptor.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "bwm_adaptor", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0,
     "Comment": "业务侧接入新版带宽系统适配程序", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 152, "CreatedAt": "2020-09-10T12:49:40+08:00", "UpdatedAt": "2020-09-10T12:49:40+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "haproxy-qat", "ProjectID": "project-63b6c0b3",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "zone", "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "HAProxy QAT", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 153, "CreatedAt": "2020-09-10T13:31:52+08:00", "UpdatedAt": "2020-09-10T13:31:52+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "qat", "ProjectID": "project-eedae9e2",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "zone", "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "QAT依赖包：openssl qat qat_engine", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
     "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 154, "CreatedAt": "2020-09-15T10:57:06+08:00", "UpdatedAt": "2020-09-15T10:57:06+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "mtail_traffic", "ProjectID": "project-1c200f1b",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "", "IsUse": 0, "IsDocker": 0, "DockerBucket": "", "DockerAlias": "",
     "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0,
     "ClusterGroup": 0, "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 155, "CreatedAt": "2020-09-23T11:42:58+08:00", "UpdatedAt": "2020-09-23T11:42:58+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uhost-mongodb", "ProjectID": "project-b325eb17",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:uhostsre/uhost-mongodb.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "hub.ucloudadmin.com", "DockerAlias": "sre-uhost", "Unit": "process",
     "ConfArea": "set", "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "",
     "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 156, "CreatedAt": "2020-10-21T14:53:04+08:00", "UpdatedAt": "2020-10-21T14:53:26+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uhost-access-docker",
     "ProjectID": "project-7762c93f", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:uhostsre/uhost-access.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "sre-uhost", "DockerAlias": "uhost-access", "Unit": "host", "ConfArea": "set",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "3.13.9", "StableConfVersion": "v0.0.152", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 157, "CreatedAt": "2020-10-21T14:57:03+08:00", "UpdatedAt": "2020-10-21T14:57:54+08:00",
     "ProjectName": "uhost", "ProductName": "uhost", "ServiceName": "uhost-access", "ProjectID": "project-72898d82",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:uhostsre/uhost-access.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "sre-uhost", "DockerAlias": "uhost-access", "Unit": "host", "ConfArea": "set",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "3.13.9", "StableConfVersion": "v0.0.152", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 158, "CreatedAt": "2020-10-26T14:11:54+08:00", "UpdatedAt": "2020-10-26T14:11:54+08:00",
     "ProjectName": "udisk", "ProductName": "udisk", "ServiceName": "udisk-api", "ProjectID": "project-caee73f6",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:block/api_udisk.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "host", "ConfArea": "region",
     "EffectRange": "global", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "udisk api ",
     "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "",
     "Usage": "", "SecUsage": ""},
    {"ID": 159, "CreatedAt": "2020-10-26T14:45:55+08:00", "UpdatedAt": "2020-10-26T14:45:55+08:00",
     "ProjectName": "udisk", "ProductName": "udisk", "ServiceName": "thor", "ProjectID": "project-0751f983",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:block/thor.git", "IsUse": 0, "IsDocker": 0,
     "DockerBucket": "", "DockerAlias": "", "Unit": "process", "ConfArea": "set", "EffectRange": "zone", "GrpcMode": 0,
     "HttpMode": 1, "PromMode": 0, "ClusterGroup": 0, "Comment": "udisk thor", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 161, "CreatedAt": "2020-10-27T14:22:17+08:00", "UpdatedAt": "2020-11-16T16:28:10+08:00",
     "ProjectName": "unet", "ProductName": "cnat2", "ServiceName": "cnat2bwctl", "ProjectID": "project-47c9c86a",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat2/cnat2bwctl.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "cnat2", "DockerAlias": "cnat2bwctl", "Unit": "process", "ConfArea": "set",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0,
     "Comment": "新版带宽系统 CNat2业务侧", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "v0.1.1-pre",
     "StableConfVersion": "v0.0.161", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 162, "CreatedAt": "2020-11-10T10:10:17+08:00", "UpdatedAt": "2020-11-10T10:10:17+08:00",
     "ProjectName": "unet", "ProductName": "cnat", "ServiceName": "cnatbwctl", "ProjectID": "project-cca1e713",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cnat/cnatbwctl.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "cnat", "DockerAlias": "cnatbwctl", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0,
     "Comment": "新版带宽CNat业务侧带宽管理服务", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 163, "CreatedAt": "2020-11-18T14:42:35+08:00", "UpdatedAt": "2020-11-18T14:42:35+08:00",
     "ProjectName": "unet", "ProductName": "vpn", "ServiceName": "vpnbwctl", "ProjectID": "project-844f7886",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:vpngw/vpnbwctl.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "vpngw", "DockerAlias": "vpnbwctl", "Unit": "process", "ConfArea": "zone",
     "EffectRange": "zone", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0,
     "Comment": "带宽重构 vpn带宽控制面服务", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 164, "CreatedAt": "2020-11-23T17:10:44+08:00", "UpdatedAt": "2020-11-23T17:10:44+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulbcenter", "ProjectID": "project-deb194c9",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cedric/center.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "iaas", "DockerAlias": "ulbcenter", "Unit": "host", "ConfArea": "set", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "ulb控制面与数据面核心调度服务", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 166, "CreatedAt": "2020-11-23T19:00:34+08:00", "UpdatedAt": "2020-11-23T19:00:34+08:00",
                       "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulb_private_api",
                       "ProjectID": "project-653fde33", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:cedric/api.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "iaas", "DockerAlias": "ulb_private_api", "Unit": "host", "ConfArea": "region",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "ulb_private_api服务，提供对内部访问的接口", "Code": 0, "IsGrayscale": 0, "IsBranch": 0,
                       "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 167, "CreatedAt": "2020-11-23T19:03:53+08:00", "UpdatedAt": "2020-11-23T19:03:53+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulbagent_next", "ProjectID": "project-df3cfea0",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cedric/agent.git", "IsUse": 0, "IsDocker": 0,
     "DockerBucket": "", "DockerAlias": "", "Unit": "host", "ConfArea": "set", "EffectRange": "region", "GrpcMode": 0,
     "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "数据面核心调度程序", "Code": 0, "IsGrayscale": 0,
     "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 168, "CreatedAt": "2020-11-26T12:22:18+08:00", "UpdatedAt": "2020-11-26T12:22:18+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulb_tc_bwmanager", "ProjectID": "project-f9a9e059",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulb_tc_bwmanager.git", "IsUse": 0,
     "IsDocker": 1, "DockerBucket": "iaas", "DockerAlias": "ulb_tc_bwmanager", "Unit": "process", "ConfArea": "set",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 169, "CreatedAt": "2020-11-26T15:36:38+08:00", "UpdatedAt": "2020-11-26T15:36:38+08:00",
                       "ProjectName": "unet", "ProductName": "ulb4", "ServiceName": "ulb4_bwmanager",
                       "ProjectID": "project-97de481d", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:ulb/ulb4_bwmanager.git", "IsUse": 0, "IsDocker": 1,
                       "DockerBucket": "iaas", "DockerAlias": "ulb4_bwmanager", "Unit": "process", "ConfArea": "set",
                       "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
                       "Comment": "", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
                       "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 170, "CreatedAt": "2020-12-03T15:04:09+08:00", "UpdatedAt": "2020-12-03T15:04:09+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulb_private_proxy", "ProjectID": "project-ca49e3f5",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:cedric/proxy.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "iaas", "DockerAlias": "ulb_private_proxy", "Unit": "host", "ConfArea": "region",
     "EffectRange": "global", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "ulb私有api全网网关系统", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 171, "CreatedAt": "2020-12-30T16:39:53+08:00", "UpdatedAt": "2020-12-30T16:39:53+08:00",
     "ProjectName": "unet", "ProductName": "eip", "ServiceName": "sharebandwidth_postpaid",
     "ProjectID": "project-d33cdacf", "ProjectType": 1, "IsStatus": 1,
     "GitRepo": "git@git.ucloudadmin.com:utraffic/sharebandwidth_postpaid.git", "IsUse": 0, "IsDocker": 1,
     "DockerBucket": "utraffic", "DockerAlias": "sharebandwidth_postpaid", "Unit": "process", "ConfArea": "region",
     "EffectRange": "global", "GrpcMode": 0, "HttpMode": 1, "PromMode": 1, "ClusterGroup": 0,
     "Comment": "非标：共享带宽后付费（每月底进行后付费共享带宽结算）", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 172, "CreatedAt": "2020-12-30T19:33:14+08:00", "UpdatedAt": "2020-12-30T19:33:14+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "uwaf-html-resource", "ProjectID": "project-a38c26a5",
     "ProjectType": 0, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/uwaf-html-resource.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "host", "ConfArea": "region",
     "EffectRange": "region", "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0,
     "Comment": "uwaf-html-resource", "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "",
     "StableConfVersion": "", "ServiceCode": "", "Usage": "", "SecUsage": ""},
    {"ID": 173, "CreatedAt": "2021-01-06T17:50:32+08:00", "UpdatedAt": "2021-01-06T17:50:32+08:00",
     "ProjectName": "unet", "ProductName": "ulb7", "ServiceName": "ulbmonitor2", "ProjectID": "project-3b0c12b5",
     "ProjectType": 1, "IsStatus": 1, "GitRepo": "git@git.ucloudadmin.com:ulb/ulbmonitor2.git", "IsUse": 0,
     "IsDocker": 0, "DockerBucket": "", "DockerAlias": "", "Unit": "host", "ConfArea": "set", "EffectRange": "region",
     "GrpcMode": 0, "HttpMode": 0, "PromMode": 0, "ClusterGroup": 0, "Comment": "ulbmonitor2 新架构ulb7的监控服务", "Code": 0,
     "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "", "ServiceCode": "", "Usage": "",
     "SecUsage": ""}, {"ID": 174, "CreatedAt": "2021-01-07T11:25:09+08:00", "UpdatedAt": "2021-01-07T11:25:09+08:00",
                       "ProjectName": "unet", "ProductName": "eip", "ServiceName": "unetfe-reconciliation",
                       "ProjectID": "project-bd3fe907", "ProjectType": 1, "IsStatus": 1,
                       "GitRepo": "git@git.ucloudadmin.com:utraffic/unetfe-reconciliation.git", "IsUse": 0,
                       "IsDocker": 1, "DockerBucket": "utraffic", "DockerAlias": "unetfe-reconciliation",
                       "Unit": "process", "ConfArea": "region", "EffectRange": "region", "GrpcMode": 0, "HttpMode": 1,
                       "PromMode": 1, "ClusterGroup": 0,
                       "Comment": "EIP对账服务：1.数据库中已删除的EIP检查资源系统和计费状态。2.数据库中已删除的共享带宽检查资源系统和计费状态。3.检查t_ip_object表中是否存在一个外网ip有多条数据的情况。4.查找主机已经删除但是绑定关系还存在的数据",
                       "Code": 0, "IsGrayscale": 0, "IsBranch": 0, "StableVersion": "", "StableConfVersion": "",
                       "ServiceCode": "", "Usage": "", "SecUsage": ""}], "RetCode": 0}
import http.client
import json



if __name__ == '__main__':
    res = []
    test_data = []
    for v in data['Data']:
        if v.get("StableConfVersion", "") != "" and v.get("StableVersion", "") != "":
            res.append(v)

    for i in res:
        svc = i.get("StableVersion", "")
        v = svc.split("-")
        if len(v) >= 2:
            svc_version = "v" + v[1]
        else:
            svc_version = svc
        test_data.append({
            "product": i.get("ProductName", ""),
            "server_name": i.get("ServiceName", ""),
            "server_version": svc_version,
            "config_version": i.get("StableConfVersion", ""),
            "diff": "region:1000001,az:4001"

        })
    print(test_data)
    import requests

    # for i in test_data:
    # payload = json.dumps(test_data[0])

    headers = {
        'content-type': "application/json",
        'cache-control': "no-cache",
    }
    import pprint

    rr = []
    for i in test_data[2:]:
        payload = json.dumps(i)
        r = requests.post("http://localhost:8080/v1/cc/compare", data=payload, headers=headers)
        pprint.pprint(r.json())
        x = r.json()
        try:
            if x['data']['count'] != "ok":
                rr.append(x)
        except Exception as e:
            pprint.pprint(e)
            pprint.pprint(payload)
    pprint.pprint(rr)
